### ISSUE TITLE
Support Subpixel Antialiasing

### ISSUE THREAD

**Issue by sekkit** [vercel/geist-font#28]
the font is blur in Rider

**Comment by mario-d-s** [comment]
I have no idea where the issue lies, but after just installing the font from GH releases and trying it out in Rider, it does look pretty weird:
![Rider_sample](https://github.com/vercel/geist-font/assets/4290238/00fd1858-1e96-46ae-8636-09baf2dfb86c)

First off, this is size 14 which matches size 13 on most other fonts (the size I'm accustomed to).

Oddities (imo):

- `op)`
- the `b`
- `2` looks slightly bolder than `1`

Comparing with the "playground" on https://vercel.com/font:

![Rider_compare](https://github.com/vercel/geist-font/assets/4290238/8fc987ff-bcc2-4760-8a46-54809349d03c)
![Vercel_compare](https://github.com/vercel/geist-font/assets/4290238/2a86febd-a604-4c5f-a366-701705cc6694)

**Comment by JohnPhamous** [comment]
@sekkit @mario-d-s, are you using the variable font?

**Comment by mario-d-s** [comment]
@JohnPhamous I did not immediately realize what you meant with that. I installed all the `.ttf` files from the zip (on Windows) without really looking at them, and **now** I see there is a `GeistVF.ttf` in there which also explains why I got the weird "Geist Regular is already installed" popup. So yes, I _am_ using the variable font (related: #11).

The "non-variable" actually even looks **worse**:
![Geist non-variable in Rider](https://github.com/vercel/geist-font/assets/4290238/efa97f2f-5ab9-4d5a-ac42-0c53abc2fe60)

**Comment by guidoferreyra** [comment]
Font rendering can vary a lot depending on the platform (rider/site/notepad), altough autohinting was improved on fonts on the latest release https://github.com/vercel/geist-font/releases/tag/1.3.0
