### ISSUE TITLE
Geist Mono not recognised as 'Fixed Width' on macOS

### ISSUE THREAD

**Issue by brzzdev** [vercel/geist-font#33]
**Font Name:**
Geist Mono

**Steps to Reproduce:**
1. Install .otf files on macOS
2. Filter Font Book by fixed width fonts
3. Geist Mono is not listed

**Expected Behavior:**
Geist Mono should be listed here as it is a monospaced font

**Environment (please complete the following information):**
 - OS: macOS
 - Version of the Font: 1.0

**Comment by walnutjon** [comment]
Also in Windows 11 (22H2). Installed from the geist-mono zip file.

![Screenshot 2023-11-01 172122](https://github.com/vercel/geist-font/assets/5074185/9d9e4648-2a78-4050-873e-b61e71c718a7)

**Comment by wayne-shih** [comment]
This'll be coz not all the metric width is the same (600) -- notably the fractions (1200) and ligatures (1200, 1800, 2400, 3000), even though the fractions and ligatures are multiple of the base 600 they are still different thus the system thinks it's not a mono font. 

Would need to tweak all of them to 600.  

<img width="378" alt="CleanShot 2023-11-02 at 19 19 53@2x" src="https://github.com/vercel/geist-font/assets/51947763/3dd1433e-b934-4393-b59d-8ae46f21400e">

<img width="454" alt="CleanShot 2023-11-02 at 19 20 12@2x" src="https://github.com/vercel/geist-font/assets/51947763/67804b16-d92a-4821-a5a8-a39f8c7b96f9">

----

JetBrains is a good implementation example. 

Take `~~>` as an example, instead of making the metric width 1800 (600*3), the ligature glyph itself retains as 600 and on the contextual ligature on tilde tilde greater it substitutes the 2 tilde with a `SPC` character (basically an empty glyph) and the `asciitilde_asciitilde_greater.liga` sits snuggly as the last character space and visually overlaps on top of the previous 2 empty spots. 

<img width="697" alt="CleanShot 2023-11-02 at 19 04 45@2x" src="https://github.com/vercel/geist-font/assets/51947763/fb49b297-6a03-4566-9dc0-89d75cf3cbc9">

<img width="953" alt="CleanShot 2023-11-02 at 19 08 23@2x" src="https://github.com/vercel/geist-font/assets/51947763/57dee237-5049-4a93-b964-36d46123de38">

---- 

Fractions on the other hand... 

Geist Mono fractions are essentially double the width (1200 = 600*2), however these are a single unicode character... 

<img width="1277" alt="CleanShot 2023-11-02 at 19 12 49@2x" src="https://github.com/vercel/geist-font/assets/51947763/b1a007e5-46a7-497a-948e-aaa84787b150">

suggest it gets redrawn as a single 600 width character, ie. JetBrains Mono example : 
> <img width="391" alt="CleanShot 2023-11-02 at 19 14 46@2x" src="https://github.com/vercel/geist-font/assets/51947763/7a20018a-1c68-4301-912b-283ee9f8f003">

I would also remove the fractions ligature, what's happening here is I am typing 3 characters (ie. `1` `/` `2`) to have it render as 1 character with a 2 character visual width... instead of 3.

**Comment by guidoferreyra** [comment]
It’s fixed now on version 1.4.0
